name: Build PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
        key: ${{ hashFiles('Makefile') }}
    - name: Install cargo deps
      run: make dev-deps
    - name: Generate website
      run: make build
