name: Deploy Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
        key: ${{ hashFiles('Makefile') }}
    - name: Install cargo deps
      run: make ci-deps
    - name: Generate website
      run: make build
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "v(.*)"
    - name: Create tag folder
      env:
        TAG_NAME: ${{ steps.tagName.outputs.tag }}
      run: |
        mkdir -p docs/$TAG_NAME && mv book/html/* docs/$TAG_NAME
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs
        clean: false
